apiVersion: v1
kind: Namespace
metadata:
  name: customer-a
  labels:
    tenant: customer-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: customer-a-infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: customer-a
  labels:
    tenant: customer-a
spec:
  fluentd:
    disablePvc: true
    logLevel: trace
  controlNamespace: customer-a-infra
  watchNamespaceSelector:
    matchLabels:
      tenant: customer-a
  routeConfig:
    enableTelemetryControllerRoute: true
    disableLoggingRoute: true
    tenantLabels:
      tenant: customer-a
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
  namespace: customer-a
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
  match:
  - select:
      labels:
        app.kubernetes.io/name: log-generator
  localOutputRefs:
    - loki-customer-a
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: loki-customer-a
  namespace: customer-a
spec:
 loki:
   url: http://loki-customer-a.customer-a.svc.cluster.local:3100
   configure_kubernetes_labels: true
   buffer:
     timekey: 1m
     timekey_wait: 5s
     timekey_use_utc: true
