apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    tenant: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: infra
  labels:
    tenant: infra
spec:
  loggingRef: infra
  fluentd:
    disablePvc: true
    logLevel: trace
  controlNamespace: infra
  watchNamespaceSelector:
    matchExpressions:
      - key: tenant
        operator: Exists
  routeConfig:
    enableTelemetryControllerRoute: false
    disableLoggingRoute: false
    tenantLabels:
      tenant: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all
  namespace: infra
spec:
  loggingRef: infra
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
  match:
  - select:
      labels:
        app.kubernetes.io/name: log-generator
  globalOutputRefs:
    - loki-infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki-infra
  namespace: infra
spec:
  loggingRef: infra
  loki:
    url: http://loki-infra.infra.svc.cluster.local:3100
    configure_kubernetes_labels: true
    buffer:
      timekey: 1m
      timekey_wait: 5s
      timekey_use_utc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: infra
spec:
  loggingRef: infra
  inputTail:
    storage.type: filesystem
  positiondb:
    hostPath:
      path: ""
  bufferStorageVolume:
    hostPath:
      path: ""
  network:
    connectTimeout: 2
  metrics: {}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: LoggingRoute
metadata:
  name: tenants
spec:
  source: infra
  targets:
    matchExpressions:
      - key: tenant
        operator: Exists
