apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Collector
metadata:
  name: cluster
spec:
  debug: true
  dryRunMode: true
  controlNamespace: collector
  tenantSelector:
    matchLabels:
      collect: "true"
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  labels:
    collect: "true"
  name: ingress
spec:
  persistenceConfig:
    enableFileStorage: true
  transform:
    name: parse-nginx
    flattenData: true
    logStatements:
      - context: log
        statements:
        - set(cache["body_str"], Decode(body, "utf-8"))

        # Parse nginx access log format
        # Example: "GET /api/click/blue HTTP/1.1" 200 75 "http://frontend.local/" "Mozilla/5.0..." 313 0.002 [frontend-frontend-8080] [] 10.244.0.61:8080 75 0.002 200 c2e67709723d5eb8466527075f752b55

        - set(cache["request_line"], Split(cache["body_str"], "\"")[1]) where IsMatch(cache["body_str"], "\"")
        - set(cache["referer"], Split(cache["body_str"], "\"")[3]) where Len(Split(cache["body_str"], "\"")) > 3
        - set(cache["user_agent"], Split(cache["body_str"], "\"")[5]) where Len(Split(cache["body_str"], "\"")) > 5
        - set(log.attributes["user_agent.original"], cache["user_agent"]) where cache["user_agent"] != nil and cache["user_agent"] != "-"

        # Example: "GET /api/click/blue HTTP/1.1"
        - set(log.attributes["http.request.method"], Split(cache["request_line"], " ")[0]) where cache["request_line"] != nil
        - set(log.attributes["url.path"], Split(cache["request_line"], " ")[1]) where cache["request_line"] != nil

        # Example: "http://frontend.local/" -> extract scheme and server address
        - set(log.attributes["url.scheme"], Split(cache["referer"], "://")[0]) where cache["referer"] != nil and cache["referer"] != "-" and IsMatch(cache["referer"], "://")
        - set(cache["host_with_path"], Split(cache["referer"], "://")[1]) where cache["referer"] != nil and cache["referer"] != "-" and IsMatch(cache["referer"], "://")
        - set(log.attributes["server.address"], Split(cache["host_with_path"], "/")[0]) where cache["host_with_path"] != nil
  logSourceNamespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: ingress-nginx

# The following ConfigMap can be used to configure nginx to emit access logs in a custom format
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   labels:
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/instance: ingress-nginx
#   name: ingress-nginx-controller
#   namespace: ingress-nginx
# data:
#   hsts: "false"
#   log-format-upstream: '[$time_iso8601, $proxy_protocol_addr, $proxy_add_x_forwarded_for,
#     $req_id, $remote_user, $bytes_sent, $request_time, $status, $host, $server_protocol,
#     $uri, $args, $request_length, $request_time, $request_method, $http_referer, $http_user_agent]'
