apiVersion: v1
kind: Namespace
metadata:
  name: customer-b-infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: customer-b
  labels:
    tenant: customer-b
spec:
  fluentd:
    disablePvc: true
    logLevel: trace
  controlNamespace: customer-b-infra
  watchNamespaceSelector:
    matchLabels:
      tenant: customer-b
  routeConfig:
    enableTelemetryControllerRoute: true
    disableLoggingRoute: true
    tenantLabels:
      tenant: customer-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: all
  namespace: customer-b
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
  match:
  - select:
      labels:
        app.kubernetes.io/name: log-generator
  localOutputRefs:
    - loki-customer-b
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: loki-customer-b
  namespace: customer-b
spec:
  loki:
    url: http://loki-customer-b.customer-b.svc.cluster.local:3100
    configure_kubernetes_labels: true
    buffer:
      timekey: 10s
      timekey_wait: 5s
      timekey_use_utc: true
